### ISSUE TITLE
code in the PNN.py file has little error

### ISSUE THREAD

**Issue by liuzhiyong01** [lambdaji/tf_repos#1]
outer = tf.reshape(tf.einsum('aik,ajk->aijk', p, q), [-1, num_pairs*embedding_size*embedding_size])
should be:
outer = tf.reshape(tf.einsum('api,apj->apij', p, q), [-1, num_pairs*embedding_size*embedding_size])

**Comment by lambdaji** [comment]
谢谢纠正，outer PNN没经过测试，忘了注释掉
