### ISSUE TITLE
有个小疑问，为什么我增加batch size GPU内存却没有增加。batch size = 100000

### ISSUE THREAD

**Issue by Ken-Con** [lambdaji/tf_repos#11]
按理batch size增加同时运算的GPU需要内存也会增加

**Comment by Ken-Con** [comment]
@lambdaji 代码里不是配置了吗？我运行的是DeepFM。GPU内存不管batch多大都是335M，而且GPU Volatile一直是0.不知道哪儿有问题

**Comment by Ken-Con** [comment]
@lambdaji 😓，我以为那是指明使用0号gpu，我是tf新手。谢谢了。感觉这task GPU根本没啥用。卡在读取数据上。你有什么好办法提高速度吗？

**Comment by laochangxin** [comment]
这里的代码input_fn已经是pipeline读取的了，你可能需要把文件split出多份，调大input_fn里map的num_parallel_batches。通过显存大小和GPU利用率的情况能知道是否是读取数据到达瓶颈。

**Comment by Ken-Con** [comment]
@lambdaji 谢谢

**Comment by murdonson** [comment]
@laochangxin  这个代码是python2写的吗

**Comment by laochangxin** [comment]
@murdonson 我是用Py2跑的lambdaji的代码,2.7.5, tf 1.10.0

**Comment by Ken-Con** [comment]
@laochangxin 感情我一直@错人了。。。

**Comment by JayJJChen** [comment]
@Ken-Con 
> ok，谢谢了。我发现这个task对batch size非常敏感。我在小数据集上使用batch 10000时学习率使用0.0001没作用，使用0.01效果就不错。而但batch 100时学习率0.01不错。感觉差距好大。不知为什么？难道是因为batch大时内部负类样本太多？

batch越大，梯度方向越稳定，就可以使用更大的lr。反之在batch偏小的时候，梯度方向不稳定，lr如果太大将会无法收敛，需要相应减小。
